version: "3.9"

services:
  ##
  # Fast API Backend
  #
  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: "uvicorn app.main:app --host 0.0.0.0 --port ${BACKEND_PORT}"

  ##
  # NuxtJS Frontend
  #
  frontend:
    build: ./frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: "yarn dev"
